# ==============
# COMMON IMPORTS
# ==============

from .forecast_meta_data_common import *

from .forecast_meta_data_object import ForecastMetaDataObject
from .forecast_meta_data_id import ForecastMetaDataSeriesIdGenerator
from .forecast_meta_data_range import ForecastMetaDataRange
#from .forecast_meta_data_series import ForecastMetaDataSeries
#from .forecast_meta_data_factory import ForecastMetaDataFactory




# =======
# CLASSES
# =======


# ForecastMetaDataContainer
# Root object for all Meta Data objects which hold other meta-data objects
class ForecastMetaDataContainer():

    # CLASS VARIABLES
    # ---------------
    class ContainerType(str, Enum):
        STEP = "step"
        GROUP = "group"


    # INSTANCE VARIABLES
    # ------------------

    # From Object
    id: str = None
    parent = None
    #parent: Type['ForecastMetaDataContainer']  = None

    # meta_data attributes
    display_name: str = None


    container_type: ContainerType = None                # type of container this is (STEP, GROUP, etc.)
    id_generator: ForecastMetaDataSeriesIdGenerator = None  # an id generator


    # data structure to hold the container's objects
    _model: dict[str, ForecastMetaDataObject] = None


    # pointers to ForecastMetaDataSeries IDs which are often needed
    _input_id: str = None   # this is the FormatDataSeries which is an INPUT into this container (i.e. external to the container)
    _first_id: str = None   # this is the FIRST FormatDataSeries generated by the container
    _last_id: str = None    # this is the last FormatDataSeries which was generated in the container (up until this point)


    # convenience attributes based on _last_id
    _last_data_type: ForecastDataSeriesMetaDataDataType = None
    _last_display_type: ForecastDataSeriesMetaDataDataType = None


    # defaults for use to set actions (FormatMetaDataSeries) if not overriden
    default_data_type: ForecastDataSeriesMetaDataDataType = None
    default_display_type: ForecastDataSeriesMetaDataDataType = None
    default_validation = None
    default_pred: list[str] = None
    default_update_last_id: bool = None
    default_verify_integrity: bool = None
    default_drop_dups: bool = None


    # __init__
    # Adds initializing all meta-data attributes to None.
    #  
    # INPUTS:
    #   Any of the meta-data attributes can be set
    # 
    # OUTPUTS:
    #   NA

    def __init__(self, 
                 id_prefix: str, 
                 display_name: str, 
                 container_type: ContainerType, 
                 id: str = None, 
                 parent: Type['ForecastMetaDataContainer'] = None, 
                 id_generator: ForecastMetaDataSeriesIdGenerator = None,
                 input_id: str = None,
                 default_data_type: ForecastDataSeriesMetaDataDataType = None,
                 default_display_type: ForecastDataSeriesMetaDataDataType = None,
                 default_validation = None,
                 default_pred: list[str] = None,
                 default_update_last_id: bool = None,
                 default_verify_integrity: bool = None,
                 default_drop_dups: bool = None,
                 *args, 
                 **kwargs):

        # set container_type
        self.container_type: ForecastMetaDataContainer.ContainerType = container_type
       
       # id_generator
       # ZIV
        if(id_generator is None):
            self.id_generator: ForecastMetaDataSeriesIdGenerator = ForecastMetaDataSeriesIdGenerator(container = self)
        else:
            self.id_generator = id_generator

        # _model
        self._model: dict[str, ForecastMetaDataObject] = {}

        # input_id
        if input_id is not None:
            self.input_id: str = input_id
        elif parent is not None:
            self.input_id: str = parent.last_id()
        else:
            self._input_id = None  # NOTE:  We bypass the setter to set the value internally to None

        # first_id
        self._first_id = None # NOTE:  We bypass the setter to set the value internally to None

        # last_id
        self._last_id = None # NOTE:  We bypass the setter to set the value internally to None


        # initialize defaults for new action (also making class variables to instance variables)

        # default_data_type
        if(default_data_type is not None):
            self.default_data_type: ForecastDataSeriesMetaDataDataType = default_data_type
        else:
            self.default_data_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.FLOAT
        
        # default_display_type
        if(default_display_type is not None):
            self.default_display_type: ForecastDataSeriesMetaDataDataType = default_display_type
        else:
            self.default_display_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT
        
        # default_validation
        if(default_validation is not None):
            self.default_validation = default_validation
        else:
            self.default_validation = [{ForecastDataSeriesMetaDataValidationSchema.INPUT_RESTRICTION: ForecastDataSeriesMetaDataValidateInputRestrictions.READ_ONLY}],
        
        # default_pred
        if(default_pred is not None):
            self.default_pred: list[str] = default_pred
        else:
            self.default_pred: list[str] = None

        # default_update_last_id
        if(default_update_last_id is not None):
            self.default_update_last_id: bool = default_update_last_id
        else:
            self.default_update_last_id: bool = None
        
        # default_verify_integrity
        if(default_verify_integrity is not None):
            self.default_verify_integrity: bool = default_verify_integrity
        else:
            self.default_verify_integrity: bool = None
        
        # default_drop_dups
        if(default_drop_dups is not None):
            self.default_drop_dups: bool = None
        else:
            self.default_drop_dups: bool = None


        if(id is None):
            self.id = self.id_generator.gen_rel_id(prefix = id_prefix)
        else:
            self.id = id

        self.parent = parent

        # kick up to parent (meta_data_object) to set the rest
        #super().__init__(id = id, display_name = display_name, parent = parent, *args, **kwargs)        




    # Getter / setter methods
    # -----------------------

    # input_id
    @property
    def input_id(self) -> str:
        return self._input_id
    
    @input_id.setter
    def input_id(self, value: str):
        # guarantees that we only set input_id ONCE
        # only add the input id if there isn't one already
        if self._input_id is None:
            self._input_id = value

            # if this is a legit input id, then chances are future values will use the same
            # formatting, so if there is a parent that this came from, set the last_data_type
            # and last_display_type if they are currently None
            if(self.parent is not None):
                if(self._last_data_type is not None):
                    self._last_data_type = self.parent[value].get_data_type()

                if(self._last_display_type is not None):
                    self._last_display_type = self.parent[value].get_display_type()


    # last_id
    @property
    def last_id(self) -> str:
        return self._last_id
    
    @last_id.setter
    def last_id(self, value: str):
        if value is not None:
            self._last_id = value

            # update the last_data_type and last_display_type 
            # (convenience because the next action will probably be in the same format as the previous action)
            self._last_data_type = self[value].get_data_type()
            self._last_display_type = self[value].get_display_type()

            # the assumption is that the currently worked on group is the latest group in a container, so if we
            # are setting it's last_id, than this last_id needs to ripple all the way up to all containers of this group
            if(self.parent is not None):
                self.parent.last_id = value

            # if it's a legit last_id, it could be a first_id as well, so if no first id, set it here
            if(self._first_id is None):
                self.first_id = value

        else:
            raise ValueError(f"\n* set last_id:  Error, None value submitted to last_id")


    # first_id   
    @property
    def first_id(self) -> str:
        return self._first_id
    
    @first_id.setter
    def first_id(self, value: str):
        # guarantees that we only set first_id ONCE
        if self._first_id is None:
            self._first_id = value

            # if this is a legit first_id, then chances are future values will use the same
            # formatting, so if there is a parent that this came from, set the last_data_type
            # and last_display_type if they are currently None
            if(self.parent is not None):
                if(self._last_data_type is not None):
                    self._last_data_type = self.parent[value].get_data_type()

                if(self._last_display_type is not None):
                    self._last_display_type = self.parent[value].get_display_type()


    # last_data_type
    @property
    def last_data_type(self) -> str:
        return self._last_data_type
    
    @last_data_type.setter
    def last_data_type(self, value: str):
        # we do not allow external updating of last_data_type so discard it here
        return


    # last_display_type
    @property
    def last_display_type(self) -> str:
        return self._last_display_type

    @last_display_type.setter
    def last_display_type(self, value: str):
        # we do not allow external updating of last_display_type so discard it here
        return





    # iterator interface(s)
    # ---------------------
    def __iter__(self):
        return self._model.__iter__()

    def __next__(self):
        return self._model.__next__()

    def keys(self):
        return(self._model.keys())
    
    def values(self):
        return(self._model.values())
    
    def items(self):
        return(self._model.items())




    # dict/list interface implementation 
    # ----------------------------------
    def __getitem__(self, item: int | str) -> ForecastMetaDataObject:
        
        if isinstance(item, int):
            item = list(self._model.keys())[item]

        return(self._model[item])
    
    
    def __setitem__(self, key: int | str, value: ForecastMetaDataObject):

        if isinstance(key, int):
            key = list(self._model.keys())[key]

        value.parent = self
        self._model[key] = value




    # with interface implementation
    # -----------------------------
    def __enter__(self):
        return(self)
    
    def __exit__(self, exc_type, exc_value, tradeback):

        if(exc_type is None) and (exc_value is None) and (tradeback is None):
            return True
        else:
            print(f"Problem occured:  {exc_type.__name__}: {exc_value}")
    

    # __str__
    # Return a printable version of the class instance
    #  
    # INPUTS:
    #   NA
    # 
    # OUTPUTS:
    #   Str with printable version of instance data

    def __str__(self):
        results = ""

        # add meta-data attributes
        results += f"container_type = {self.container_type}\n"

        results += super().__str__()
        results += "\n"

        if(len(self._model) > 0):
            results += "\n"

        # iterate on all objects in the dict and print their meta-data
        for obj in self._model:
            results += f"{self._model[obj]}\n\n"

        return results

    
    # to_dict
    # Serialize this object as a dictionary
    
    def to_dict(self) -> dict:
        out_dict = super().to_dict()
        out_dict["container_type"] = self.container_type
        out_dict["model"] = self._model

        return(out_dict)




    # FACTORY METHODS TO CREATE DIFFERENT CONTAINER TYPES
    # ---------------------------------------------------

    # create different CONTAINER types
    # --------------------------------

    # GROUP

    # add_group
    # Create a new GROUP object, in the factory
    #  
    # INPUTS:
    #   ident (optional: 4) - number of spaces to indent the JSON
    # 
    # OUTPUTS:
    #   JSON string
    def add_group(self,
                  display_name: str,
                  id: str = None,
                  new_defaults: bool = False,
                  new_id_gen: bool = False) -> Type['ForecastMetaDataGroup']:
        
        # pass the id_generator to the child
        if not new_id_gen:
            id_generator = self.id_generator
        else:
            id_generator = None

        new_group = ForecastMetaDataGroup(display_name = display_name, 
                                          id = id, 
                                          parent = self, # set parent to current container 
                                          id_generator = id_generator)
        self._model[new_group.id] = new_group

        # pass defaults through
        if not new_defaults:
            new_group.default_data_type = self.default_data_type
            new_group.default_display_type = self.default_display_type
            new_group.default_validation = self.default_validation
            new_group.default_pred = self.default_pred
            new_group.default_update_last_id = self.default_update_last_id
            new_group.default_verify_integrity = self.default_verify_integrity
            new_group.default_drop_dups = self.default_drop_dups

        return(new_group)


    # STEP

    # _add_step
    # Hidden method to create a new STEP object in the factory
    #  
    # INPUTS:
    #   display_name
    #   step_type
    #   ident (optional: 4) - number of spaces to indent the JSON
    # 
    # OUTPUTS:
    #   JSON string

    def _add_step(self,
                  display_name: str,
                  step_type: ForecastDataSeriesMetaDataStepTypes,
                  id_prefix: str = None, 
                  id: str = None,
                  new_defaults: bool = False,
                  new_id_gen: bool = False) -> Type['ForecastMetaDataStep']:
        
        # pass the id_generator to the child
        if not new_id_gen:
            id_generator = self.id_generator
        else:
            id_generator = None

        new_step = ForecastMetaDataStep(display_name = display_name, 
                                        step_type = step_type, 
                                        id_prefix = id_prefix, 
                                        id = id, 
                                        parent = self, # set parent to current container 
                                        id_generator = id_generator)

        self._model[new_step.id] = new_step


        # pass defaults through
        if not new_defaults:
            new_step.default_data_type = self.default_data_type
            new_step.default_display_type = self.default_display_type
            new_step.default_validation = self.default_validation
            new_step.default_pred = self.default_pred
            new_step.default_update_last_id = self.default_update_last_id
            new_step.default_verify_integrity = self.default_verify_integrity
            new_step.default_drop_dups = self.default_drop_dups

        return(new_step)
    

    # define the PUBLIC step creation methods that we offer
    def add_epidemiology(self, display_name: str, id: str = None, new_defaults = False, new_id_gen = False) -> Type['ForecastMetaDataStep']:
        return self._add_step(id_prefix = "Epidemiology", display_name = display_name, step_type = ForecastDataSeriesMetaDataStepTypes.EPIDEMIOLOGY, id = id)

    def add_pricing(self, display_name: str, id: str = None, new_defaults = False, new_id_gen = False) -> Type['ForecastMetaDataStep']:
        return self._add_step(id_prefix = "Pricing", display_name = display_name, step_type = ForecastDataSeriesMetaDataStepTypes.PRICING, id = id)

    def add_delay(self, display_name: str, id: str = None, new_defaults = False, new_id_gen = False) -> Type['ForecastMetaDataStep']:
        return self._add_step(id_prefix = "Delay", display_name = display_name, step_type = ForecastDataSeriesMetaDataStepTypes.DELAY, id = id)

    def add_pop_cut(self, display_name: str, id: str = None, new_defaults = False, new_id_gen = False) -> Type['ForecastMetaDataStep']:
        return self._add_step(id_prefix = "Pop_cut", display_name = display_name, step_type = ForecastDataSeriesMetaDataStepTypes.POPULATION_CUT, id = id)

    def add_segment(self, display_name: str, id: str = None, new_defaults = False, new_id_gen = False) -> Type['ForecastMetaDataStep']:
        return self._add_step(id_prefix = "Segment", display_name = display_name, step_type = ForecastDataSeriesMetaDataStepTypes.SEGMENT, id = id)

    def add_summation(self, display_name: str, id: str = None, new_defaults = False, new_id_gen = False) -> Type['ForecastMetaDataStep']:
        return self._add_step(id_prefix = "Summation", display_name = display_name, step_type = ForecastDataSeriesMetaDataStepTypes.SUMMATION, id = id)

    def add_treatment(self, display_name: str, id: str = None, new_defaults = False, new_id_gen = False) -> Type['ForecastMetaDataStep']:
        return self._add_step(id_prefix = "Treatment", display_name = display_name, step_type = ForecastDataSeriesMetaDataStepTypes.TREATMENT, id = id)




    # create different SERIES / ACTION types
    # --------------------------------------


    # _add_action
    # Hidden method to create a new action object in the factory
    #  
    # INPUTS:
    #   display_name
    #   step_type
    #   ident (optional: 4) - number of spaces to indent the JSON
    # 
    # OUTPUTS:
    #   JSON string
    
    def _add_action(self,
                    action_pred_type: ForecastDataSeriesMetaDataActionPredTypes,
                    id_prefix: str,
                    display_name: str,
                    action: ForecastDataSeriesMetaDataAction,
                    data_type: ForecastDataSeriesMetaDataDataType,
                    display_type: ForecastDataSeriesMetaDataDataType,
                    data_values: list | pd.Series = None,
                    validation:  list[dict] = None,
                    ranges: list[ForecastMetaDataRange] = None,
                    pred: list[str] = None,
                    args: dict = None,
                    objs: dict = None,
                    update_last_id: bool = None,
                    verify_integrity: bool = None,
                    drop_dups: bool = None,
                    id: str = None,
                    id_postfix: str = None,
                    **kwargs) -> Type['ForecastMetaDataSeries']:
        
        # generate an ID
        if(id is None):
            id = f"{self.id_generator.gen_rel_id(prefix = id_prefix)}_{id_postfix}"



        # set any DEFAULT values that need to be set

        # data_type
        if(data_type is None):
            data_type = self.default_data_type

        # display_type
        if(display_type is None):
            display_type = self.default_display_type

        # validation
        if(validation is None):
            validation = self.default_validation

        # pred
        if(pred is None):
            pred = self.default_pred

        # update_last_id
        if(update_last_id is None):
            update_last_id = self.default_update_last_id

        # verify_integrity
        if(verify_integrity is None):
            verify_integrity = self.default_verify_integrity

        # drop_dups
        if(drop_dups is None):
            drop_dups = self.default_drop_dups



        # determine if we can automatically add any information to the pred based on the
        # ForecastDataSeriesMetaDataActionPredTypes.  This is a major convience as many of our actions form:
        # take some ACTION on the last_id(), so if we can figure out where to auto-fill that last id, the 
        # using the api will be much clear and less error prone

        # class ForecastDataSeriesMetaDataActionPredTypes(str, Enum):
        #     NO_PREDS = "no_preds" # this action does not take any preds (i.e. DATES)
        #     ONE_PRED = "one_pred" # this action take ONE AND ONLY ONE pred (i.e. YEAR_TO_MONTH, MONTH_TO_YEAR)
        #     TWO_OR_MORE_PREDS = "two_or_more_preds" # this action takes AT LEAST TWO preds (i.e SUM, PROD, SUB, etc.)


        #     INPUTS
        #     DATES
        #     VALUES = "values" # display read-only values
        #     SUM = "sum" # sum up a series of col ids (in preds) or constants
        #     TOTAL = "total" # same as sum, but may be treated different visually
        #     PROD = "prod" # multiply a series of col ids (preds) or constants
        #     SUB = "sub"  # subtract a series of col ids (preds) or constants
        #     YEAR_TO_MONTH = "year_to_month" # convert a yearly series to monthly
        #     MONTH_TO_YEAR = "month_to_year" # convert a monthly series to yearly

        if (pred is None):
            num_preds = 0
        else:
            num_preds = len(pred)

        match action_pred_type:
            # INPUTS, DATES, VALUES
            case ForecastDataSeriesMetaDataActionPredTypes.NO_PREDS:
                pass

            # YEAR_TO_MONTH, MONTH_TO_YEAR
            case ForecastDataSeriesMetaDataActionPredTypes.ONE_PRED:
                if num_preds == 0:
                    pred = self.last_id()

            # SUM, TOTAL, PROD, SUB
            case ForecastDataSeriesMetaDataActionPredTypes.TWO_OR_MORE_PREDS:
                if num_preds < 2:
                    pred.insert(0, self.last_id())


        # create the new action / series
        new_action = ForecastMetaDataSeries(id = id,
                                            display_name = display_name, 
                                            action = action,
                                            ranges = ranges,
                                            data_type = data_type,
                                            display_type = display_type,
                                            data_values = data_values,
                                            validation =  validation,
                                            pred = pred,
                                            args = args,
                                            objs = objs,
                                            parent = self, # set the parent to this container
                                            **kwargs)
        
        # TODO: verify_integrity implementation

        # TODO: drop_dups implementation

        self._model[new_action.id] = new_action

        # update_last_id
        # check if we should update the last_id for this (this means its a row of values for later use)
        if(update_last_id):
            self.last_id = new_action.id

            # if this is a legit last_id, then it can also serve as a first_id, IF NO first_id is already defined
            if self.first_id is None:
                self.first_id = new_action.id

        return(new_action)
    


    # define the PUBLIC action creation methods that we offer
    # NOTE ON CODING STYLE HERE:
    #   since these are all very long with lots of the same args being defined / passed, for each action,
    #   have used a single line instead of one line per argument.  HOWEVER:  in the _add_action() call, 
    #   I've moved the arguments to the front which change from action to action, to make them easier to see

    # add_action:
    #                 display_name: str,
    #                 pred: list[str] = None,
    #                 data_values: list | pd.Series = None,

    #                 BLANK MOST OF THE TIME
    #                 ranges: list[ForecastMetaDataRange] = None,
    #                 id_postfix: str = None,

    #                 DEFAULTS TYPICALLY COVER
    #                 data_type: ForecastDataSeriesMetaDataDataType,
    #                 display_type: ForecastDataSeriesMetaDataDataType,
    #                 validation:  list[dict] = None,
    #                 args: dict = None,
    #                 objs: dict = None,
    #                 update_last_id: bool = None,
    #                 verify_integrity: bool = None,
    #                 drop_dups: bool = None,
    #                 id: str = None,
    #                 **kwargs) -> Type['ForecastMetaDataSeries']:
    
    # def _add_action(self,
    #                 action_pred_type: ForecastDataSeriesMetaDataActionPredTypes,
    #                 id_prefix: str,
    #                 display_name: str,
    #                 action: ForecastDataSeriesMetaDataAction,
    #                 data_type: ForecastDataSeriesMetaDataDataType,
    #                 display_type: ForecastDataSeriesMetaDataDataType,
    #                 data_values: list | pd.Series = None,
    #                 validation:  list[dict] = None,
    #                 ranges: list[ForecastMetaDataRange] = None,
    #                 pred: list[str] = None,
    #                 args: dict = None,
    #                 objs: dict = None,
    #                 update_last_id: bool = None,
    #                 verify_integrity: bool = None,
    #                 drop_dups: bool = None,
    #                 id: str = None,
    #                 id_postfix: str = None,
    #                 **kwargs) -> Type['ForecastMetaDataSeries']:


    def _add_action(self,
                    action_pred_type: ForecastDataSeriesMetaDataActionPredTypes, id_prefix: str, display_name: str, action: ForecastDataSeriesMetaDataAction, data_type: ForecastDataSeriesMetaDataDataType, display_type: ForecastDataSeriesMetaDataDataType, data_values: list | pd.Series = None, validation:  list[dict] = None,
                    ranges: list[ForecastMetaDataRange] = None,
                    pred: list[str] = None,
                    args: dict = None,
                    objs: dict = None,
                    update_last_id: bool = None,
                    verify_integrity: bool = None,
                    drop_dups: bool = None,
                    id: str = None,
                    id_postfix: str = None,
                    **kwargs) -> Type['ForecastMetaDataSeries']:
        pass


    # DATES
    def add_dates(self, display_name: str, values: pd.Series | list, id_postfix: str = None, id: str = None):
        self._add_step()

    # INPUTS
    def add_input(self, display_name: str, values: pd.Series | list, validation: dict[ForecastDataSeriesMetaDataValidationSchema, Any], id_postfix: str = None, data_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT, display_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT, id: str = None, update_last_id: bool = True):
        pass

    # VALUES
    def add_values(self, display_name: str, values: pd.Series | list, id_postfix: str = None, data_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.FLOAT, display_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT, validation: dict[ForecastDataSeriesMetaDataValidationSchema, Any] = FORECAST_READ_ONLY_VALIDATION, id: str = None, update_last_id: bool = True):
        pass

    # COPY
    def add_copy(self, display_name: str, pred: str, id_postfix: str = None, update_last_id: bool = True):
        pass

    # SUM
    def add_sum(self, display_name: str, pred: list[str], id_postfix: str = None, data_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.FLOAT, display_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT, validation: dict[ForecastDataSeriesMetaDataValidationSchema, Any] = FORECAST_READ_ONLY_VALIDATION, id: str = None, update_last_id: bool = True):
        pass

    # PROD
    def add_prod(self, display_name: str, pred: list[str], id_postfix: str = None, data_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.FLOAT, display_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT, validation: dict[ForecastDataSeriesMetaDataValidationSchema, Any] = FORECAST_READ_ONLY_VALIDATION, id: str = None, update_last_id: bool = True):
        pass

    # SUB
    def add_sub(self, display_name: str, pred: list[str], id_postfix: str = None, data_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.FLOAT, display_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT, validation: dict[ForecastDataSeriesMetaDataValidationSchema, Any] = FORECAST_READ_ONLY_VALIDATION, id: str = None, update_last_id: bool = True):
        pass

    # YEAR_TO_MONTH
    def add_ytm(self, display_name: str, pred: str, id_postfix: str = None, data_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.FLOAT, display_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT, validation: dict[ForecastDataSeriesMetaDataValidationSchema, Any] = FORECAST_READ_ONLY_VALIDATION, id: str = None, update_last_id: bool = True):
        pass

    # MONTH_TO_YEAR
    def add_mty(self, display_name: str, pred: str, id_postfix: str = None, data_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.FLOAT, display_type: ForecastDataSeriesMetaDataDataType = ForecastDataSeriesMetaDataDataType.INT, validation: dict[ForecastDataSeriesMetaDataValidationSchema, Any] = FORECAST_READ_ONLY_VALIDATION, id: str = None, update_last_id: bool = True):
        pass

        


    # def add_input(self, display_name: str, id_postfix: str, data_type: ForecastDataSeriesMetaDataDataType, display_type: ForecastDataSeriesMetaDataDataType, data_values: list | pd.Series = None, validation:  list[dict] = None, ranges: list[ForecastMetaDataRange] = None, pred: list[str] = None, args: dict = None, objs: dict = None, update_last_id: bool = None, verify_integrity: bool = None, drop_dups: bool = None, id: str = None, **kwargs) -> Type['ForecastMetaDataSeries']:
    #     id_postfix = f"Inputs_{id_postfix}" if (id_postfix is not None) else "Inputs"
    #     return self._add_action(action_pred_type = ForecastDataSeriesMetaDataActionPredTypes.NO_PREDS, action = ForecastDataSeriesMetaDataAction.INPUT, validation = validation, id_postfix = id_postfix, id_prefix = self.id, data_type = data_type, display_type =  display_type, data_values = data_values, ranges = ranges, pred = pred, args = args, objs = objs, update_last_id = update_last_id, verify_integrity = verify_integrity, drop_dups = drop_dups, id = id, **kwargs)

    # # DATES
    # def add_dates(self, display_name: str, data_values: list | pd.Series, id_postfix: str = None, drop_dups: bool = True, id: str = None, **kwargs) -> Type['ForecastMetaDataSeries']:
    #     id_postfix = f"Dates_{id_postfix}" if (id_postfix is not None) else "Dates"
    #     return self._add_action(action_pred_type = ForecastDataSeriesMetaDataActionPredTypes.NO_PREDS, action = ForecastDataSeriesMetaDataAction.DATES, data_type = ForecastDataSeriesMetaDataDataType.DATE, display_type =  ForecastDataSeriesMetaDataDataType.DATE, validation = FORECAST_READ_ONLY_VALIDATION, id_postfix = id_postfix, id_prefix = self.id, display_name = display_name, ranges = None, pred = None, args = None, objs = None, update_last_id = False, drop_dups = drop_dups, verify_integrity = False, data_values = data_values, id = id, **kwargs)

    # # VALUES
    # def add_values(self, display_name: str, id_postfix: str, data_type: ForecastDataSeriesMetaDataDataType, display_type: ForecastDataSeriesMetaDataDataType, data_values: list | pd.Series = None, validation:  list[dict] = None, ranges: list[ForecastMetaDataRange] = None, pred: list[str] = None, args: dict = None, objs: dict = None, update_last_id: bool = None, verify_integrity: bool = None, drop_dups: bool = None, id: str = None, **kwargs) -> Type['ForecastMetaDataSeries']:
    #     id_postfix = f"Values_{id_postfix}" if (id_postfix is not None) else "Values"
    #     return self._add_action(action_pred_type = ForecastDataSeriesMetaDataActionPredTypes.NO_PREDS, id_postfix = id_postfix, action = ForecastDataSeriesMetaDataAction.INPUT, validation = validation, id_prefix = self.id, data_type = data_type, display_type =  display_type, data_values = data_values, ranges = ranges, pred = pred, args = args, objs = objs, update_last_id = update_last_id, verify_integrity = verify_integrity, drop_dups = drop_dups, id = id, **kwargs)








# ForecastMetaDataStep
# Holds all the meta data for a pandas series (i.e. column) we need to render a forecast model
class ForecastMetaDataStep(ForecastMetaDataContainer):
    
    # CLASS VARIABLES
    # ---------------
    NON_VALUE_ACTIONS = [ForecastDataSeriesMetaDataAction.STEP_INIT]

    
    # INSTANCE VARIABLE
    step_type: ForecastDataSeriesMetaDataStepTypes = None


    # __init__
    # Adds initializing all meta-data attributes to None.
    #  
    # INPUTS:
    #   Any of the meta-data attributes can be set
    # 
    # OUTPUTS:
    #   NA

    def __init__(self,
                 display_name: str, 
                 step_type: ForecastDataSeriesMetaDataStepTypes,
                 id_postfix: str = None, 
                 id: str = None,
                 parent: Type['ForecastMetaDataContainer'] = None,
                 id_generator: ForecastMetaDataSeriesIdGenerator = None,
                 *args, 
                 **kwargs):
        
        # initialize all instance variables
        self.step_type: ForecastDataSeriesMetaDataStepTypes = step_type

        if(id_postfix is None):
            id_prefix = "Step"


        super().__init__(id_prefix = id_prefix,
                         display_name = display_name,
                         container_type = ForecastMetaDataContainer.ContainerType.STEP, 
                         id = id, 
                         parent = parent,
                         id_generator = id_generator,
                         *args, 
                         **kwargs)   


        


    # __str__
    # Return a printable version of the class instance
    #  
    # INPUTS:
    #   NA
    # 
    # OUTPUTS:
    #   Str with printable version of instance data

    def __str__(self):

        # add meta-data attributes
        results = f"step_type = {self.step_type}\n"

        # call parent's str function
        results += super().__str__()

        return results
    
    # to_dict
    # Serialize this object as a dictionary
    
    def to_dict(self) -> dict:
        out_dict = super().to_dict()
        out_dict["step_type"] = self.step_type

        return(out_dict)

    
# ForecastMetaDataGroup
# Holds all the meta data for a pandas series (i.e. column) we need to render a forecast model
class ForecastMetaDataGroup(ForecastMetaDataContainer):
    
    # CLASS VARIABLES
    # ---------------

    
    # INSTANCE VARIABLE
    # -----------------


    # __init__
    # Adds initializing all meta-data attributes to None.
    #  
    # INPUTS:
    #   Any of the meta-data attributes can be set
    # 
    # OUTPUTS:
    #   NA

    def __init__(self, 
                 display_name: str, 
                 id: str = None,
                 parent: Type['ForecastMetaDataContainer'] = None,
                 id_generator: ForecastMetaDataSeriesIdGenerator = None,
                 *args, 
                 **kwargs):
        
        super().__init__(id_prefix = "Group", 
                         display_name = display_name,
                         container_type = ForecastMetaDataContainer.ContainerType.GROUP,
                         id = id,  
                         parent = parent,
                         id_generator = id_generator, 
                         *args, **kwargs)     

        # initialize all instance variables
        pass


    # __str__
    # Return a printable version of the class instance
    #  
    # INPUTS:
    #   NA
    # 
    # OUTPUTS:
    #   Str with printable version of instance data

    def __str__(self):

        # add meta-data attributes
        results = "\n"

        # call parent's str function
        results += super().__str__()

        return results

        
    # to_dict
    # Serialize this object as a dictionary
    
    def to_dict(self) -> dict:
        out_dict = super().to_dict()

        return(out_dict)


    # to_json
    # Serialize this object to a JSON string
    #  
    # INPUTS:
    #   ident (optional: 4) - number of spaces to indent the JSON
    # 
    # OUTPUTS:
    #   JSON string

    def to_json(self, indent:int = 4) -> str:
        import json
        return json.dumps(self, default = FormatMetaDataObjectsJsonSerializer, indent=indent)
