#####################################################################
# forecast_renderer_excel_TB.py
#
# Implements the a summation component.  It's already implemented everywhere
# this just makes it explicit (for visual presentation purposes)
# 
# INPUTS:  DataFrame
# OUTPUTS:  DataFrame
#
#####################################################################


from typing import List, Tuple
from datetime import datetime
import pandas as pd
import numpy as np
from langflow.schema.dataframe import DataFrame, Data


# FORECAST SPECIFIC IMPORTS
# =========================
from langflow.base.forecasting_common.constants import FORECAST_INT_TO_SHORT_MONTH_NAME, ForecastModelInputTypes, ForecastModelTimescale
from langflow.base.forecasting_common.models.forecast_data_model import ForecastDataModel


# COMPONENT SPECIFIC IMPORTS
# ==========================
from enum import Enum
import shutil
from openpyxl import Workbook, worksheet, cell, load_workbook
from openpyxl.styles import Protection




# CLASSES
# =======

# Enum of supporting DataModel Schema
class ForecastModelSchema(str, Enum):
    ACTION = "action"
    ID = "id"
    PRED = "pred"
    DISPLAY_NAME = "display_name"



# Enum of supporting render action types
class ForecastModelActions(str, Enum):
    DATES = "dates"
    VALUE_INPUT = "value_input"
    MULTIPLY_PRED = "multiply_pred"
    SUM_PRED = "sum_pred"

# Enum of supported ForecastDataModel data types
# Internally ForecastDataModel only has dates and floats, this is really how it should show
# those internal types (for example: a float rendered as an INT might now show the decimals)
class ForecastDataModelRenderType(str, Enum):
    INT = "int"
    FLOAT = "float"
    DATE = "date"
    PERCENT = "percent"
    CURRENCY = "currency"


# Enum of of the different types of input restrictions
class ForecastRenderInputRestrictions(str, Enum):
    READ_WRITE = "read_write"
    READ_ONLY = "read_only"
    TOKEN_CHECK = "token_check"


class IdToCellReferenceMap():
    # INSTANCE VARIABLES
    # id_to_ref_map - a dictionary which maps all ForecastDataModel IDs to the tab and the cell reference of their rows in excel

    def __init__(self):
        # create instance variables
        self.id_to_ref_map = {}

    def add(self, id: str, tab_name: str, cell_ref: str):
        if(id in self.id_to_ref_map.keys()):
            raise ValueError(f"* add: error, id '{id}' already exists in map:\n{self.id_to_ref_map.keys()}")

        self.id_to_ref_map[id] = {"tab": tab_name, "ref": cell_ref}

    def get(self, id: str) -> Tuple[str, str]:
        try:
            full_ref = self.id_to_ref_map[id]
            tab_name = full_ref["tab"]
            cell_ref = full_ref["ref"]
            return(tab_name, cell_ref)
        except:
            raise ValueError(f"* get: error, id '{id}' not found in map:\n{self.id_to_ref_map.keys()}")




# ForecastRendererExcel
# Class which renders a Forecast Model player for excel using an Time Based model
class ForecastRendererExcelTB():
    # CONSTANTS
    # =========

    # FORECAST DATA MODEL CONSTANTS
    DATAMODEL_ACTION_COL = "action"
    DATAMODEL_PRED_COL = "input_rows"


    # EXCEL PLAYER CONSTANTS
    EXCEL_REQUIRED_WORKBOOK_TABS = ["Summary"]
    EXCEL_START_ROW = 4 #NOTE:  All ROW references are 1's indexed, not zero-indexed per openpyxl
    EXCEL_START_COL = 2 #NOTE:  All COLUMN references are 1's indexed, not zero-indexed per openpyxl

    # styles
    EXCEL_STYLES_WORKSHEET_HEADER = "Headline 1"

    # READ/WRITE
    EXCEL_STYLES_READ_WRITE_INT = "Input"
    EXCEL_STYLES_READ_WRITE_FLOAT = "Input"
    EXCEL_STYLES_READ_WRITE_DATE = "Input"
    EXCEL_STYLES_READ_WRITE_PERCENT = "Input"
    EXCEL_STYLES_READ_WRITE_CURRENCY = "Input"

    # READ ONLY
    EXCEL_STYLES_READ_ONLY_INT = "Normal"
    EXCEL_STYLES_READ_ONLY_FLOAT = "Normal"
    EXCEL_STYLES_READ_ONLY_DATE = "Normal"
    EXCEL_STYLES_READ_ONLY_PERCENT = "Normal"
    EXCEL_STYLES_READ_ONLY_CURRENCY = "Normal"


    # VARIABLES
    # =========

    # CLASS VARIABLES
    input_type = ForecastModelInputTypes.TIME_BASED

    # INSTANCE VARIABLES
    # ------------------
    # start_year - start year of forecast
    # start_month - start of fiscal year (or 1 - January for calendar year)
    # timescale - the minimum unit for a period in the forecast (can be MONTH or YEAR)
    # num_periods - the number of periods in the forecast
    # forecast_model - the forecast model generated by the DESIGNER
    # output_location - the location to put the rendered player
    # hasTemplate - True if the render uses a template, False if not
    # template_location (optional) - the location to load the template
    # template (optional) - a template to use when developing the player
    # template_num_sheets - the number of sheets that came with the template (all our sheets must go in front of those)

    # player_model - the object model for the player being developed (openpyxl.Workbook class)
    # row_trackers - dict of ints, each tab in the spreadsheet is the key, and the current location to add a new row is the int
    # id_cellref_map - holds the mapping from all IDs to excel cell references (full references including tab name and cell coordinates)



    # CONSTRUCTOR
    # ===========
    # The constructor gets all the variables which are specific to this particular renderer vs generic to all implementers of RENDER INTERFACE.
    # In the case of this excel renderer, this include if we are using a template and where that template is located, as well as the location to
    # save the output file to
    #
    # INPUTS:
    #   output_location - location to save the output player
    #   template_location (optional) - if we are using a template file, where is the file located
    # 
    # OUTPUTS:
    #   N/A

    def __init__(self,
                 output_location: str, 
                 template_location: str = None):

        self.output_location = output_location

        if(template_location is None):
            self.hasTemplate = False
            self.template_location = None
        else:
            self.hasTemplate = True
            self.template_location = template_location



    
    # RENDER INTERFACE FUNCTIONS
    # ==========================

    # render_player
    # RENDER INTERFACE:  render a player and return to the caller function 
    #  
    # INPUTS:
    #     data - a list of int or floats (first series)
    #     start_year - the start year for the forecast
    #     num_years - number of years for the forecast
    #     input_type - is the forecast type a 'Time Based Input' or 'Single Input' (may be an issue if there are both of them)
    #     start_month - 
    # 
    # OUTPUTS:
    #   DataFrame
    def render_player(self, start_year, start_month, num_periods, timescale, forecast_model, *args, **kwargs):

        # save these as instance variables
        self.start_year = start_year
        self.start_month = start_month
        self.num_periods = num_periods
        self.timescale = timescale
        self.forecast_model = forecast_model

        # initial setup when rendering
        self._initialize_new_render()

        # generate the model
        self._build_model_excel()

        # save the model
        self._finalize_new_render(self.output_location)


    # MAIN RENDER FUNCTIONS
    # =====================

    def _initialize_new_render(self):
        # create new workbook or copy template
        if(self.hasTemplate):
            # since openpyxl has no object copy method for a workbook, we have to copy the template workbook
            # to the new filename and then open that
            shutil.copyfile(self.template_location, self.output_location)
            self.player_model = load_workbook(self.output_location)

        else:
            self.player_model = Workbook()

            # if any worksheets were created in the default object, get rid of them
            num_sheets = len(self.player_model.sheetnames)

            if(num_sheets > 0):
                for i in range(num_sheets):
                    ws = self.get_ws(0)
                    self.player_model.remove(ws)
                    
        
        # generate the core tabs if they don't exist
        self._generate_core_tabs()

        # initialize the current row trackers
        self.row_trackers = {}
        for tab in self.EXCEL_REQUIRED_WORKBOOK_TABS:
            self.row_trackers[tab] = self.EXCEL_START_ROW    # NOTE:  All row references are 1-based based per openpyxl

        # set up the mapper between ForecastDataModel id's and cell references in excel
        self.id_cellref_map = IdToCellReferenceMap()

        



    def _finalize_new_render(self, output_location: str):
        self.player_model.save(output_location)

        # TODO:  figure out what the return here, the intent is to provide a way to
        # return things in realtime if a renderer doesn't save to a file (for example a dynamic JSON file)
        # but have to figure out what (if anything) to return when it does save a file
        return(self.player_model)




    
    def _build_model_excel(self):
        print(f"forecast_model:\n{self.forecast_model}")

        # iterate through the forecast model, column by column, dispatching as needed
        for i in range(len(self.forecast_model)):
            curr_row = self.forecast_model[self.forecast_model.columns[i]]

            # determine the action
            print(curr_row.attrs[str(ForecastModelSchema.ACTION)])


    # RENDER PRIMITIVES
    # =================

    # _add_values_row
    # Add a row of values to the model
    #  
    # INPUTS:
    #   
    #   tab = the tab to add it to
    #   values = the series of values to add
    #   type = the data type (for formatting purposes)
    #   restrictions = the set of restrictions on data entry
    # 
    # OUTPUTS:
    #   worksheet

    def _add_values_row(self, id: str, tab_name: str, values: list, type: ForecastDataModelRenderType, restriction: ForecastRenderInputRestrictions):
        if(tab_name not in self.row_trackers.keys()):
            raise ValueError(f"* add_input_row:  error, requested tab '{tab_name}' not in the list of tabs\n{self.row_trackers.keys()}")
        
        # set-up for the adding
        ws = self.player_model[tab_name]
        curr_row = self.row_trackers[tab_name]
        num_values_to_add = len(values)

        # go cell by cell adding the row values
        for i in range(num_values_to_add):
            curr_cell = ws.cell(row = curr_row, column = i + self.EXCEL_START_COL)
            curr_cell.value = values[i]
            self._add_input_restrictions(curr_cell, type, restriction)
        
        # increment the row_tracker for this tab
        self._track_add_row(id = id, tab_name = tab_name, cell_ref = curr_row)

    
    # EXCEL PRIMITIVES
    # ================
    
    # handles the boilerplate bookkeeping whenever a new row is added to the model
    def _track_add_row(self, id, tab_name, cell_ref):
        # add the id of the row to our mapper
        self.id_cellref_map.add(id = id, tab_name = tab_name, cell_ref = cell_ref)

        # increment our row tracker for this tab, so we know location of next row to add
        self.row_trackers[tab_name] += 1


    # handles setting any formatting and read/write access based on the input restrictions to this cell
    def _add_input_restrictions(self, curr_cell: cell, render: ForecastDataModelRenderType, restriction: ForecastRenderInputRestrictions):

        # if token check is requested, the figure out if the current value matches the ForecastDataModel approved editable values token
        # if it does, make it read_write, otherwise make it read only
        if(restriction == ForecastRenderInputRestrictions.TOKEN_CHECK):
            if(curr_cell.value == ForecastDataModel.EDITABLE_VALUES_TOKEN):
                restriction = ForecastRenderInputRestrictions.READ_WRITE
            else:
                restriction = ForecastRenderInputRestrictions.READ_ONLY

        # based on the restriction and the data type, apply cell protection and the appropriate style
        match restriction:
            case ForecastRenderInputRestrictions.READ_WRITE:
                match render:
                    case ForecastDataModelRenderType.INT:
                        curr_cell.style = self.EXCEL_STYLES_READ_WRITE_INT
                    case ForecastDataModelRenderType.FLOAT:
                        curr_cell.style = self.EXCEL_STYLES_READ_WRITE_FLOAT
                    case ForecastDataModelRenderType.DATE:
                        curr_cell.style = self.EXCEL_STYLES_READ_WRITE_DATE
                    case ForecastDataModelRenderType.PERCENT:
                        curr_cell.style = self.EXCEL_STYLES_READ_WRITE_PERCENT
                    case ForecastDataModelRenderType.CURRENCY:
                        curr_cell.style = self.EXCEL_STYLES_READ_WRITE_CURRENCY
                    case _:
                        raise ValueError(f"* _add_input_restrictions:  invalid Data Model Render type '{type}' requested for cell at '{curr_cell.coordinate}'")
                    
                curr_cell.protection = Protection(locked = False, hidden = False)


            case ForecastRenderInputRestrictions.READ_ONLY:
                match render:
                    case ForecastDataModelRenderType.INT:
                        curr_cell.style = self.EXCEL_STYLES_READ_ONLY_INT
                    case ForecastDataModelRenderType.FLOAT:
                        curr_cell.style = self.EXCEL_STYLES_READ_ONLY_FLOAT
                    case ForecastDataModelRenderType.DATE:
                        curr_cell.style = self.EXCEL_STYLES_READ_ONLY_DATE
                    case ForecastDataModelRenderType.PERCENT:
                        curr_cell.style = self.EXCEL_STYLES_READ_ONLY_PERCENT
                    case ForecastDataModelRenderType.CURRENCY:
                        curr_cell.style = self.EXCEL_STYLES_READ_ONLY_CURRENCY
                    case _:
                        raise ValueError(f"* _add_input_restrictions:  invalid Data Model Render type '{type}' requested for cell at '{curr_cell.coordinate}'")
                    
                curr_cell.protection = Protection(locked = True, hidden = False)

            case _:
                raise ValueError(f"* _add_input_restrictions:  invalid input restriction type '{restriction}' requested for cell at '{curr_cell.coordinate}'")



    # HELPER FUNCTIONS 
    # ================

    # _initialize_new_render HELPERS
    # ------------------------------


    # _finalize_new_render HELPERS
    # ----------------------------


    # _build_new_renderer HELPERS
    # ---------------------------
    def _generate_core_tabs(self):
        # remove the first worksheet
        #ws = self.get_ws(0)
        #self.player_model.remove(ws)

        # get the number of worksheets in workbook
        self.template_num_sheets = len(self.player_model.sheetnames)
        

        # generate the core tabs of the model
        for tab in self.EXCEL_REQUIRED_WORKBOOK_TABS:
            self.create_ws(tab)

        print(f"sheetnames:{self.player_model.sheetnames}")

    
    # OTHER HELPERS
    # -------------

    # create_ws
    # Standardizes the creation of a tab, including adding headers and anything else need
    #  
    # INPUTS:
    #   tab = either the name of a worksheet or the 0-based index of the worksheet in a workbook
    # 
    # OUTPUTS:
    #   worksheet

    def create_ws(self, tab: str) -> worksheet:
        ws = self.safe_create_ws(tab)
        ws['A1'] = tab
        ws['A1'].style = self.EXCEL_STYLES_WORKSHEET_HEADER
        ws.protection.sheet = True

        return(ws)


    # safe_create_ws
    # Simple convenience function to check if a worksheet already exists before creating it
    #  
    # INPUTS:
    #   tab = either the name of a worksheet or the 0-based index of the worksheet in a workbook
    # 
    # OUTPUTS:
    #   worksheet
    def safe_create_ws(self, tab: str) -> worksheet:

        # check if a tab exists before creating it, if it does, leave it alone
        try:
            ws = self.player_model[tab]
        except:
            sheet_index = len(self.player_model.sheetnames) - self.template_num_sheets
            ws = self.player_model.create_sheet(tab, index = sheet_index)

        return(ws)


    # remove_ws
    # Simple convenience function to remove a sheet by either index or name using get_ws
    #  
    # INPUTS:
    #   tab = either the name of a worksheet or the 0-based index of the worksheet in a workbook
    # 
    # OUTPUTS:
    #   None
    def remove_ws(self, tab: str | int):
        self.player_model.remove(self.get_ws(tab))

    # get_ws
    # Simple convenience function to enable all other worksheet functions to access a worksheet by name or index
    #  
    # INPUTS:
    #   tab = either the name of a worksheet or the 0-based index of the worksheet in a workbook
    # 
    # OUTPUTS:
    #   worksheet
    def get_ws(self, tab: str | int) -> worksheet:
        if isinstance(tab, str):
            ws = self.player_model[tab]
        elif isinstance(tab, int):
            ws = self.player_model[self.player_model.sheetnames[tab]]
        else:
            raise ValueError(f"*  get_ws:  invalid 'tab' type: {type(tab)}, value: {tab}")
        
        return(ws)


    

    

